= 2018.02.19 - 2018.02.25

=== 2018.02.19

===== 할 일 
* [*] 오늘 배운 독해, 문법 복습 및 과제하기
** [*] 독해
** [*] 문법 
* [*] 앱 12개를 만들며 배우는 Swift4 & iOS11 아이폰 iOS 개발 강좌 듣고 프로젝트 진행하기
** [*] 섹션 8. 항공권 검색 UI 만들기
* [*] 영리한 프로그래밍을 위한 알고리즘 강좌
** [*] 3. 정렬 => 기본 정렬 알고리즘, 합정렬

===== 느낀 점
* 나는 실력 있는 개발자들은 집중하면 금방 뚝딱뚝딱 만들고 잘하는 것을 부럽기도 하면서 질투하기도 한다. 시작한지 얼마 안되었지만 '꾸준히 한다고 따라잡을 수 있을까?' 의문이 들었다.
하지만, 창천향로님이 작성한 https://brunch.co.kr/@jojoldu/23[_장편소설 쓰기_] 포스트를 보면서 이러한 의문에 대해서 어느 정도 확신을 가질 수 있게 되었다.
* 평생 백수가 아닌 이상 언젠가 취업을 해야 하고 설 연휴 때, 내가 가고 싶은 회사에 대해서 생각을 해보았음
.. 기술적 토론을 할 수 있는 선배(모바일 분야가 아니더라도)가 있어야 함
.. 스톡옵션은 받지 않을 것. 성과에 따른 확실한 보상(= 돈)이 있어야 함
.. 내가 능동적으로 움직일 수 있도록 동기부여가 되는 서비스가 있어야 함. 내가 사용자가 되었을 때, 부끄럽지 않을 서비스를 말함

=== 2018.02.20

===== 할 일 
* [*] 오늘 배운 독해, 문법 복습 및 과제하기
** [*] 독해
** [*] 문법 
* [*] DB, MySQL, Transaction 기본 내용 추가 정리하기

=== 2018.02.21

===== 할 일 
* [*] 앱 12개를 만들며 배우는 Swift4 & iOS11 아이폰 iOS 개발 강좌 듣고 프로젝트 진행하기
** [*] 섹션 9. SelectCar 앱 (피커뷰 다루기)
** [*] 섹션 10. TabbarEX
** [*] 섹션 11. Weather Table
** [*] 섹션 12. Custom Cell
** [*] 섹션 13. 별자리 설명 앱
* [*] 오늘 배운 독해, 문법 복습 및 과제하기
** [*] 독해
** [*] 문법 

===== 느낀 점
* 새로 알게 된 Mac 단축키
** Command + Control + D => 웹페이지에서 모르는 단어 띄우기
** Command + Control + 1 => Show/Hide bookmarks sidebar
** Command + Option + D => Show/Hide Docks sidebar 

=== 2018.02.22

===== 할 일
* [*] 앱 12개를 만들며 배우는 Swift4 & iOS11 아이폰 iOS 개발 강좌 듣고 프로젝트 진행하기
** [*] 섹션 14. XML Parser
** [*] 섹션 15. 이미지 다운로더
** [*] 섹션 16. JSON Prasing
* [*] 오늘 배운 독해, 문법 복습 및 과제하기
** [*] 독해
** [*] 문법 
* [ ] Swift 4, iOS 프로그래밍 정리하기

===== 느낀 점
* 이벤트 처리에서 Target-Action, Delegate-DataSource 두 가지 방식에 대한 설명을 찾아보다가 아래 파일들이 뜨는데, 
https://developer.apple.com/library/content/documentation/General/Conceptual/CocoaEncyclopedia/DelegatesandDataSources/DelegatesandDataSources.html[Delegate-DataSource], 
https://developer.apple.com/library/content/documentation/General/Conceptual/CocoaEncyclopedia/Target-Action/Target-Action.html#//apple_ref/doc/uid/TP40010810-CH12-SW1[Target-Action] 
Objective-C 개념에 관한 내용인데 읽어도 괜찮을까요?

> iOS 프로그래밍 개념 중에 공통사항이라 언어랑 상관없이 사용됨. 설명이 오브젝티브C로 되어있지만 같음

* WKWebView를 이용해서 웹페이지 내용을 가져오는 동안 UIActivityIndicatorView가 실질적으로 작동하는 걸 확인하긴 했는데, 프로그래스바가 웹페이지 불러오는 동안 동작하지 않는 것처럼 보이는 이유가 내부적으로 돌아가는 프로세스가 다른가요?

> 읽어오는 동안 진행 과정을 정확하게 사파리처럼 보여주고 싶은 건가요? 그러면 DOM 분석해서 내부 동작을 모두 확인해야 함. 단순하게 안됨.
단순히 웹페이지 로딩 중에 프로그래스바가 동시에 업데이트돼서 안 보인다면 다른 문제일 수도 있음(스레드 문제라거나)

* UIResponder 문서에서 `UIKit manages the responder chain dynamically, using predefined rules to determine which object should be next to receive an event.` 이 부분에서 UIKit에서 이벤트 관리한다는 말이 어떤 의미인지 잘 이해가 되지 않습니다!

> Responder Chain 구조를 공부해야 함

* 화면 요소 속성을 struct에다가 정의해서 사용하는 소스도 있고 xib 파일로 화면 요소 속성을 정의하는 경우, 스토리보드에서 사용하는 때도 있던데.. 상황마다 다른 건가요?

> 그때그때 다름. 코드로 만들 수도 있고 인터페이스 빌더에서 스토리보드나 Xib로 할 수 있는 데 장단점이 있음. 기준에 따라 선택해서 만들수 있어야 함

* `앱 12개를 만들며 배우는 Swift4 & iOS11 아이폰 iOS 개발 강좌 듣고 프로젝트 진행하기` 강의를 다 들었다. 내가 인터넷 강의를 제대로 끝낸 것이 얼마 없는데 뿌듯함!!
* 포스트를 보다가 나의 영문 독해는 정상인가 ? 이라는 내용을 봄. 아래 내용 중 Yes가 많다면 영문 독해가 비정상이라는 내용인데, 나는 모두 Yes가 나왔다. 이에 대한 해결책은 포스트에서 일부 발췌해옴
** 글을 읽고 있으면 영어 단어 하나 하나에 대한 우리말 단어들이 머리 속을 스친다.
** 글을 읽을 때에 영어 단어들이 하나 하나 독립적으로 감지된다.
** 문장을 읽으면 부분 부분에서 해당 문법이 뚜렷하게 떠오르면서 그 뜻이 명백해진다.
** 구조가 복잡한 긴 문장을 만나면 순서를 우리말 식으로 바꿔야 하기 때문에 이해하는 시간이 오래 걸린다.
** 문장에 포함된 영어 단어들을 보는 순간 그 의미가 문맥 안에서 동시에 느껴지지는 않지만, 내가 외웠던 단어의 뜻으로 떠오른다.

> 세상 모든 언어가 그렇듯이 영어 역시 감각입니다. 단, 그 감각은 각 개인이 마음대로, 독창적으로 만들어서는 안 되는 것입니다. 그래서 그것을 '고유 감각'이라고 부릅니다.

> 그래서 영어를 습득할 때에 명심해야 할 부분은 바로 그 고유감각이 완벽하게 살아있는 글의 패턴을 익히는 일인데, 많은 양을 읽는 것도 중요하지만 원어민이 아닌 우리가 반드시 병행해야 하는 일은 가끔 완전한 문장이나 문단 또는 글 전체를 입으로, 그것도 빠른 속도로 반복해서 읽고, 가능하다면 전체를 암송하는 것입니다. 이것은 언어의 네 가지 기능을 한꺼번에 높은 수준에서 익히는 지름길입니다. 암송하는 글이 길수록 효과는 증폭됩니다. 스스로 해야 하는 이 반복 리딩은 이 글에서 지적한 어순의 문제점도 자연스럽게 극복하게 해주는 훌륭한 감각 훈련입니다.

> 글을 읽을 때에 눈은 부지런히 문장을 훑어나가고, 두뇌는 심층 의식 속에서 글쓴이와 함께 걸으며 대화 하듯이 이야기의 흐름 속에 몰입되어 있어서 단어나 문자를 의식하지 못하는 경지. 이것은 우리가 도달할 수 없는 피안의 세계가 아니고, 수많은 사람들이 쉽게 찾아가고 있는 강 건너 마을 같은 곳입니다.

* 그리고 이 글을 쓴 저자가 영어 단어 외울때, 위와 같은 맥락으로 외우라고 이야기함. 저자가 하는 이야기는 틀린 이야기가 아닌 것 같아서 이 내용 또한 발췌해서 적어둠

> 영어 단어를 빠르게 익히고, 그것도 올바른 용법과 감각을 함께 익혀서, 단어실력이 Reading, Writing, Listening, Speaking 실력에 바로 직결되게 하려면, 좋은 예문을 외우겠다는 각오로 입으로 반복해서 읽고, 귀로 반복해서 듣는 훈련을 해야 합니다. 이것이 단어공부를 통해서도 영어의 네 가지 기본 기능을 함께 훈련시킬 수 있는 유일한 길입니다. 그리고 기억력의 좋고 나쁨에 상관없이 예문은 누구나 반복적으로 읽을 수 있기 때문에 가장 쉬운 방법이기도 합니다.

=== 2018.02.23

===== 할 일 
* [*] 오픈소스 세미나 참가하기

=== 2018.02.24 - 2018.02.25

===== 할 일
* [*] Swift, iOS 프로그래밍 정리하기
* [*] 이번 주 배웠던 독해, 문법, 단어 정리하기
** [*] 단어
** [*] 문법
** [*] 독해 

===== 느낀 점
* 오픈소스 세미나를 참가하면서 중요하다고 느낀 것은 라이센스 관련 내용과 문서화인 것 같다. 결국 남들이 보기 좋게 글을 작성해야 한다는 것인데 내가 취업할 때도 비슷하지 않을까 싶다. 거짓말 하는 것은 나쁘지만 나를 잘 포장하는 것은 중요하다고 생각이 듬:)