= Mac 초기화 후 세팅하기

=== 키보드 기호 설명

|===
^| 기호 ^| 설명
| ⌘	| Command
| ⌥	| Option
| ⌃	| Control
| ⇧	| Shift
| +	| 동시 입력
| ,	| 키를 떼고 다시 입력함
|===

=== 시스템 설정

===== 미션 컨트롤 창 순서 고정
* `Mission Control > Automatically rearrange Spaces based on most recent use` => 체크 안함

===== 언어는 영어로 우선순위 설정
* `Language & Region > Preferred languages` => English > 한국어

===== 모든 텍스트 자동 변경 옵션 끄기
* `Keyboard > Text` => 모든 자동 변경 옵션 끄기

===== 클릭은 터치
* `Trackpad > Point & Click > Tab to click` => 체크함

===== 드래그는 세손가락
* `Accessibility > Mouse & Trackpad > Trackpad options...` => Enable dragging - three finger drag

=== 파인더 설정

===== 파인더 기본 폴더 설정
* `Accessibility > Mouse & Trackpad > Trackpad options...` => Enable dragging - three finger drag

===== 파일 확장자 보여주기
* `Advanced > Show all filename extensions` => 체크함

===== Cdto 설정
* https://github.com/jbtule/cdto[cdto]
* ⌘ + ⌥ 같이 누르고 아이콘을 끌면 파인더 설정할 수 있음

=== 다운로드 폴더 설정
* Downloads 폴더로 이동하고 `⌘ + J (View > Show View Options)` 를 선택함

===== 날짜 그룹 + 이름
* Arrange By => Date added, Sort By => Name

=== 필수 프로그램

===== XCode

[source, bash]
----
# 확인
$ gcc
clang: error: no input files
----

===== Homebrew

[source, bash]
----
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
----

===== Git

[source, bash]
----
# 설치
$ brew install git git-lfs

# 설정
$ git config --global user.name "Your Name"
$ git config --global user.email "you@your-domain.com"
$ git config --global core.precomposeunicode true
$ git config --global core.quotepath false
----

=== 터미널 설정

===== iTerm2
* 설치 후 설정
** 테마적용 => http://iterm2colorschemes.com[iTerm Themes]
** `Appearance > Theme` => Dark
** `Appearance > Hide scrollbars` => 체크함
** `Appearance > Show line under title bar when the tab bar is not visible` => 체크안함
** 마진수정
*** `Advanced > Height of top and bottom margins in terminal panes` => 10
*** `Advanced > Width of left and right margins in terminal panes` => 12

[source, bash]
----
# 설치
$ brew cask install iterm2
----

===== zsh with oh-my-zsh

[source, bash]
----
# zsh 설치
$ brew install zsh zsh-completions

# oh-my-zsh 설치
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# shell => zsh 쉘 변경

# zsh-syntax-highlighting
$ git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# zsh-autosuggestions
$ git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions

# ~/.zshrc 플러그인 설정 추가
plugins=(
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
)

# ~/.zshrc 적용
$ source ~/.zshrc
----

===== oh-my-zsh 테마 설정

[source, bash]
----
$ brew install nodejs # nodejs가 설치되어 있다면 skip
$ npm install --global pure-prompt

# ~/.zshrc 내용 추가
autoload -U promptinit; promptinit
prompt pure

# ~/.zshrc 적용
$ source ~/.zshrc
----

===== oh-my-zsh 팁
* 명령어가 기억나지 않으면 tab을 누름
* cd ../.. 대신 ..., ...., ....., …
* 단축명령어 - git status => gst, git pull => gl 등등
* https://github.com/robbyrussell/oh-my-zsh/wiki/Plugin:git[단축 명령어]
* https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins[플러그인]

=== 커맨드라인 애플리케이션

===== vim

[source, bash]
----
# 설치
$ brew install neovim
$ brew tap caskroom/fonts
$ brew cask install font-hack-nerd-font

# ~/.zshrc 설정 추가
$ neovim ~/.zshrc

# 내용
alias vim="nvim"
alias vi="nvim"
alias vimdiff="nvim -d"
export EDITOR=/usr/local/bin/nvim

$ source ~/.zshrc
----

===== vim 플러그인
* curl -sLf https://spacevim.org/install.sh | shell
* 설치가 완료되면 vi를 실행함. 최초 실행 시 mode 설정을 물어보고 `1을 누름`

===== vim 테마

[source, bash]
----
# ~/.SpaceVim.d/init.vim 아래 설정 추가
let g:spacevim_colorscheme = 'onedark' 
----

===== 폰트
* D2Coding 설치

===== fzf
* 증분 검색을 통하여 원하는 파일이나 히스토리를 쉽고 빠르게 찾을 수 있게 해줌 
* 정확하게 원하는 값을 입력하지 않고 일부만 입력해도 실시간으로 검색 결과를 보여줌

[source, bash]
----
$ brew install fzf

# To install useful key bindings and fuzzy completion:
$ $(brew --prefix)/opt/fzf/install


# brew 설치 후 install 명령어를 입력하면 몇 가지를 물어보는데 전부 y를 누르면 됨

# 설치 완료 후,
$ source ~/.zshrc
----

|===
^| 단축키	^| 기능
| ⌃ + T	    | 하위 디렉토리 파일 검색
| ⌃ + R	    | 히스토리 검색
| esc + C	| 하위 디렉토리 검색 후 이동
|===

===== fasd
* 열어본 파일이나 이동한 디렉토리를 기억하고 우선순위를 정해서 빠르게 검색할 수 있게 도와줌

[source, bash]
----
# 설치 
$ brew install fasd

# ~/.zshrc 설정 추가
plugins=(
  ...
  ...
  fasd
)

$ source ~/.zshrc
----

|===
^|단축키	^| 기능
| z	| 디렉토리 이동
| s	| 파일 or 디렉토리 검색
|===

* 명령어를 사용하기 위해서는 일단 디렉토리를 좀 이동하고 파일도 열어보고 해야 함
* 어느 정도 히스토리가 쌓이면 명령어를 입력해봄
* 디렉토리를 이동할 때 `z github, tab` 과 같이 일부 검색어를 입력하고 tab을 눌러서 이동함

===== tmux
* tmux는 터미널 멀티플렉서 _Terminal MUltipleXer_ 라고 함
* 하나의 화면에서 창을 여러 개 만들 수 있고 가로 분할, 세로 분할 할 수 있음
* 사용법은 공부해야 함. https://github.com/gpakosz/.tmux[tmux]

[source, bash]
----
$ brew install tmux

# ~/.zshrc 플러그인 추가
plugins=(
  ...
  ...
  tmux
)

$ source ~/.zshrc

# 태마
$ cd ~/
$ git clone https://github.com/gpakosz/.tmux.git
$ ln -s -f .tmux/.tmux.conf
$ cp .tmux/.tmux.conf.local .

# tmux는 놀랍게도 마우스를 지원함
# 윈도우 탭을 누르면 바로바로 이동하고 분할 창pane도 마우스를 누르는 창으로 포커스 이동
$ vi .tmux/.tmux.conf.local

# 아래 설정을 주석 해제함
# increase history size
set -g history-limit 10000

# start with mouse mode enabled
set -g mouse on

# force Vi mode
# really you should export VISUAL or EDITOR environment variable, see manual
set -g status-keys vi
set -g mode-keys vi
----

===== tmuxinator
* 1번 윈도우는 webpack을 실행하고 2번 윈도우는 rails server를 실행하고 3번 윈도우는 log를 실행하게 설정할 수 있음
* 사용법 익혀야 함. https://github.com/tmuxinator/tmuxinator[tmuxinator]

[source, bash]
----
$ brew install ruby
$ gem install tmuxinator

# ~/.zshrc 플러그인, 별칭 추가
plugins=(
  ...
  ...
  tmuxinator
)
alias mux="tmuxinator"
----

=== 그 외 깔아야 할 어플리케이션

===== 폰트 기본설정은 D2Coding

===== Docker

===== ngrok

===== asciinema

===== 왠만하면 brew, brew cask로 프로그램 관리하자!

[source, bash]
----
$ brew cask install java
$ brew cask install visual-studio-code 

# intelliJ, DataGrip 설치
$ brew install jetbrains-toolbox
----

===== Visual Studio Code
* VSCode Icon 플러그인 설치
* Markdown 플러그인 설치
* Asciidoc 플러그인 설치

[source, bash]
----
# AsciiDoctor가 깔려있어야 함
$ brew install asciidoctor 

$ git clone https://github.com/joaompinto/asciidoctor-vscode
$ cd asciidoctor-vscode
$ npm install
$ sudo npm install -g vsce typescript
$ vsce package
$ code --install-extension *.vsix

# 다 설치 후 재실행함
----

=== 참고
* https://subicura.com/2017/11/22/mac-os-development-environment-setup.html[본격 macOS에 개발 환경 구축하기]
* 위 내용을 많이 참고하였으며 이 외 개인적으로 사용하는 프로그램, 플러그인 추가함