= 프로그래밍 어떻게 공부할 것인가?

=== 전문성에 대한 미신들

===== 전문가는 타고남?
* Mindset
** Fixed Mindset, Growth Mindset
** `나는 왜 학습을 이야기하는가? 링크 참고`
** `아무리 노력해도 선천적 재능을 따라잡기 힘들다? 링크 참고`
** _내가 전문가가 될 수 있다는 믿음. 믿는다고 손해 보는 것은 없으니, 성장 사고관을 가지자_
* 모차르트, 아인슈타인, 체스 대가 등 천재들에 대한 일생
** 모차르트 => 모든 악보를 뜯어보고 분석함
** 체스 대가 => 일반인이 생각하지 못할 정도 많은 연습시간을 가짐
** 전문성은 타고난 것도 있지만, 후천성으로 바꿀 수 있음

===== 경력이 많으면 실력도 뛰어남?
* 입사 초기의 경력은 학습에 도움이 될 수 있지만, 그 이후 같은 일을 반복하는 경향이 있어 경력으로만 실력이 향상되지 않음
* 실력과 경력은 상관성이 거의 없음

===== 공부에 왕도가 없다?
* 독서백편 의자현보다 책을 한 번 읽고 테스트하는 것이 더 효율적임
* 더 좋은 공부법도 있고 나쁜 공부법도 있음

===== 실력에 자신감이 있다면 전문가일 것이다?
* 자신의 실력을 모르는 사람이나 없는 사람이 자기 평가를 제대로 하지 못하기 때문에 자신감을 가질 수 있음

===== 전문가는 자신이 어떻게 하는지 설명할 수 있다?
* 뛰어난 프로그래머가 있지만, 자신이 무엇을 하는지 설명을 못 할 수 있음
** 형식지
*** 책, 공식화가 되어 있음. 학교 시험 같은 것:)
** 암묵지 
*** 책이나 공식화가 되어있지 않음. 본인도 인지하지 못함
* 전문성은 암묵지 분야로 가까움. 그래서, 책을 보고 익혀도 제대로 익히지 못함

===== 전문가는 자신이 설명대로 행동한다?
* 전문가가 A를 설명하지만, B로 행동함. 그러나 이것이 거짓말이 될 수 있는가?
* 전문가는 정해진 대로 설명을 깔끔하게 하지만, 행동은 유연하고 복잡성 있음. 일반적으로 전문가가 인식을 못함

===== 전문가는 잘 가르친다?
* 프로그래밍을 잘하는 사람이지만, 가르치는 것은 다른 것

===== 이해가 잘 되면 기억에 오래 남는다?
* 어떤 책이나 강연을 보고 이해가 잘된다고 기억에 잘 남지 않음
* 이와 관련된 실험을 함. 서양화 화가에 대한 분류 체계를 A반은 선생님께서 분류 체계를 그려주면서 학생에게 설명하고 B반은 학생들이 주도적으로 공부함. 그래서 첫 번째 테스트 봤을 때 A반이 잘 이해해서 B반보다 테스트 결과가 잘 나옴. 하지만 두 번째 테스트에서 B반 성적이 잘 나옴.
A반에서 제일 공부를 많이 한 사람은 학생들을 가르치려는 선생님께서였고, B반은 학생들이 주도적으로 공부하였기 때문에 성적이 더 좋게 나옴. 왜냐하면, B반 학생들이 한 주도적인 학습을 통해 단기 기억에서 장기 기억으로 넘어감
* _단순하게 이해가 잘된다는 함정에 빠지지 말자! 결론적으로 뇌에 쥐가 놔야 오래 기억 남음_
* *_프로그래밍 공부할 때, 술술 쉽게 넘어간다면 위험할 수 있음_*

=== 전문성에 대한 과학적 근거들

===== Expertise Research(전문성 연구)
* Descriptive 
** 비전문가가 어떤 과정을 거쳐서 전문가가 되는가?
* Prescriptive 
** 어떻게 하면 높은 수준의 전문가가 효과적으로(=빠르게) 될 수 있는가?
* 1년 경험 10번? 10년 경험의 누적?
** Kevlin Henley 
*** 20 years of experience might be one year repeated 20 times
* 높은 수준의 실력 
** 자동으로 한다고 전문가가 되지 않음. 개선하고자 하는 _의도적인 노력_ 필요함
** More repetition does not automatically lead to improvement

===== 연습량
* 전문성은 자동으로 얻어지지 않음. 연습량이 중요함
* 바이올린 연주자와 피아노 연주자에 대한 베를린에서의 연구
** 세계적 수준: 10,000시간
** 전문가 수준: 8,000시간
** 음악선생: 5,000시간
** 아마추어: 2,000시간
** 연습 시간은 누적 시간
** 다른 분야에서도 비슷한 숫자를 발견함
* 업무랑 연습은 다름
** 기타리스트가 공연 시간이랑 실력은 상관성이 없음. 그러나 혼자서 연습한 시간이랑 실력은 상관성이 있음
** 체스 선수가 경기를 치른 시간은 상관없지만, 혼자 복기하거나 연습하는 것은 실력과 관계가 있음
** 직업 프로그래머도 업무와 크게 상관없다는 것을 적용할 수 있음

===== 모든 활동을 세 가지 분류
* Work
* Play
* Deliberate Practice
* 일, 노는 것, 의도적으로 연습하는 것은 서로 분리되어 있음
* 일반적 연습과 의도적 수련은 다름
** 의도적 수련
*** 계획된 수련. 내가 부족한 부분을 키우기 위해 타겟팅하여 공부함
** 무의식으로 반복적으로 하는 연습은 무의미함

=== 의도적 수련

===== 4가지 조건
* Well-defined Task 
** 잘 정의된 작업
* Appropriate Difficulty
** 적절한 난이도
* Informative Feedback
** 정보가 풍부한 피드백
* Opportunities for Repetition and Correction of Errors
** 반복과 실수 교정의 기회

===== 잘 정의된 작업, 적절한 난이도
* 잘 정의된 작업
** 그렇다면, 잘 정의된 작업과 잘 정의되지 않은 작업은 어떤 기준으로 분류할까?
** 그래픽 디자이너의 수련법 중 `잡지떼기` 라는 것이 있음. 잡지를 하나 정하고 첫 페이지부터 끝까지 사진을 보고 툴을 이용하여 작업함. 디자이너가 의도적으로 수련하는 방법
** 디자인 패턴을 열심히 써야 지에서 _일주일 동안 짰던 코드를 검토하며 이번 주 패턴을 최소 세 군데 이상 적용해봐야지_
** 목표 의도 <--> 구현 의도
** 목표 의도보다 구현 의도로 생각해야 함
* 적절한 난이도
** 프로그래밍 언어 학습의 달인은 무엇이 다른가?
*** 내가 새로운 언어를 열심히 배워야지. 프로그램 많이 만들어야 지보다 _내가 만들고자 하는 프로그램을 정하게 되면, 튜토리얼이나 1페이지부터 읽지 않음. 내가 필요한 부분을 찾아서 공부하게 됨_
*** Thompson's Rule for first-time telescope makers에서 6인치 반사경을 바로 만드는 것보다 4인치 반사경을 만들고 6인치 반사경을 만드는 것이 더 쉬움
** Cognitive Load Theory 
*** 인지적 부하 이론
*** 새 언어로 새 문제를 풀지 마라. 언어를 새로운 것으로 공부한다면 내가 풀어야 하는 문제는 쉬운 것이나 익숙한 것으로 시작하는 것이 좋음
*** 무엇을 하더라도 지루함이나 불안함을 느낀다면, 몰입이 일어나지 않음. 몰입하게 되면 행복감을 느낄 수 있음
*** `당신이 제자리걸음인 이유: 지루하거나 불안하거나 링크 참고`
** *결론은 너무 쉽거나 너무 어려운 것은 뒤로 넘기고 쉬우면 어렵게 만들어 공부하고 어려우면 쉽게 만들어 공부함*
*** 영어 단어도 아주 쉽거나, 아주 어려운 건 제외하고 애매한 단어부터 먼저 외우는 것이 좋음
*** 새로운 프로그래밍 언어를 배울 때도 목차를 보고 흥미가 끄는 것부터 진행하는 것이 좋음

===== 정보가 풍부한 피드백
* 적절한 시기에 좀 더 구체적이고 정확한 피드백
** 결과 피드백보다 과정 피드백이 더 좋음
** 행동하고 결과(피드백) 사이 시간을 줄이는 것이 좋음
* 프로그래밍 언어 학습할 때 적용법
** 피드백을 자주 받아야 함
** 컴파일러
** 단위 테스트
** 코드 리뷰
** 동료
** 커뮤니티
* 반복과 실수 교정의 기회
** 로버트 플로이드
** 어려운 알고리즘 디자인하는 방법
*** 처음부터 완벽히 새로 품. 해법의 통찰만 유지하면서 다르게 진행함. 해법이 본인이 원하는 만큼 명료하고 직접적인 것이 될 때까지 반복함. 비슷한 문제들을 일반적인 룰을 찾음. _주어진 문제를 처음부터 최고로 효율적인 방향에서 접근할 수 있는 그런 해법을 찾는 것_
** 작품 평가하는 방법 중 양으로 경쟁하는 그룹, 질로 경쟁하는 그룹을 두고 실험함. 최고 품질을 가진 작품은 양으로 평가하는 그룹에서 나옴. 질로 평가하는 그룹은 앉아서 생각만 함. 직접 해보는 것이 최고임
** Error Training 
*** 불확실성이 높은 분야일수록 많이 실수하는 것이 좋음
** 프로그래밍 언어 학습의 달인은 무엇이 다른가?
*** 같은 것을 다른 맥락에서 여러 번 해봐라. 내가 만족할만한 답이 나올 때까지 풀어봄
*** 조금씩 더 개선해봐라
*** 실수를 많이 하라
*** 완벽하게 하려고 고민하지 마라

=== 효과적인 학습법

===== 효과적인 학습법
* 연습을 위한 시험치기
** 백 번 코드 보는 것보다 한 번 쳐보는 것이 더 좋고, 쳐 보는 것보다 한 번 시험을 보는 것이 좋음
** 예제 코드가 있다면 한 번 집중해서 읽고 기억해서 최대한 테스트해 보는 것이 중요함
** `Cornell Note 링크 참고`
* 분산 연습
** 한 번 공부할 때 오랜 시간 들여서 하는 것이 좋은가? 그렇지 않음. 몰아서 하는 것보다 주기를 짧게 해서 반복적으로 하는 것이 좋음
** 책을 여러 번 읽고 테스트 한 번 하는 것보다 책을 한 번 읽고 여러 번 테스트 하는 것이 더 좋음
** `Anki 링크 참고`
* 섞어서 공부하기
** 한 과목을 쭉 하는 것보다 두-세 가지 공부할 것을 조합해서 하는 것이 좋음
* 방금 읽은 부분이 왜 그런지 자주 자문해보기, 새 정보가 이미 아는 것과 어떻게 관련 있는지(문제 푸는 단계를) 설명해보기
* 전이 효과를 높이기 위해서 
** 문제 조건 추가,삭제, 변경을 통해 반복이 있으면서 다양한 문제를 푸는 것이 좋음
** 다양한 방법으로 풀어보는 것이 중요함

===== 비효과적인 학습법
* 같은 자료를 반복해 읽기
** 그러나, 사이 간격이 길다면 효과가 높음
* 형광펜 및 밑줄 긋기
** 하지 않으니만 못한 때도 있음. 흔적이 남으니깐 공부한 것처럼 느껴지지만, 머리에 실질적으로 많이 남지 않음
* 요약하기
** 종류에 따라 효과가 다름
** 텍스트 안 보고 요약하는 것은 효과가 좋은 학습법임

=== 프로그래밍

===== 원자적 설계
* 프로그래밍 입문서 순서대로 배우는 것이 좋을까?
* 핵심 주제에 대해 쪼개서 배우는 것을 원자적 설계라고 함

===== 원자적 설계 문제점
* 구획화
** 파편적인 지식을 배우게 됨
* 분절화
** 따로 배우게 되면 통합하는 훈련이 되지 않음
* Transfer Paradox

===== 해결 방법
* 단계별로 진행하는 것이 아니라 모든 단계를 다 다루는 것이 좋음. Agile에서 Iterable이라고 함
* 전체적인 밑그림을 그리고 진행하는 것이 좋음. Part-Task보다 Whole-Task를 많이 진행해야 함

=== 질답

===== 소스리딩 능력 향상
* 소스 리딩에 대해 전문가와 비전문가 차이가 있음
* OOP 언어 관점으로 봤을 때 코드를 잘 읽는 사람은 클래스 관계, 메서드, 클래스 등을 숲을 보고, 코드를 잘 읽지 못하는 사람은 지엽적인 코드(For-Loop, 조건문)만 봄 
* 책 읽기에 대한 방법. _SQ3R_
** Survey 
*** 목차에서 내용 훑어보기
** Question 
*** 목차를 보고 생긴 질문을 정리하기
** Read 
*** 궁금한 점을 발견하였으니 적극 읽음
** Recite 
*** 책을 덮고 최대한 무슨 내용이었는지 암송하거나 인출함
** Review 
*** 기억하는 게 맞는지 확인하기
** 3R만 해도 효과적임
* 코드 분석에 적용
** 어떤 클래스나 함수나 프로젝트 구조를 파악함
** 질문이 생김
** 궁금한 점에 대해서 공격적으로 읽음. 실행 순서 상관없이 읽음
** 코드를 보지 않고 내가 읽었던 부분에 대해 정리하거나 표를 그리거나 질문했던 부분에 답을 비교해봄
** Review 과정을 통해 내가 작성한 내용과 맞는지 비교해봄

----
* 질문

실제 업무에서 소스 리딩으로 내용 파악하기 힘듬
----

===== 낯선 기술 학습하기
* 예를 들어 구글 캘린더 연동, 인증 둘 다 연관된 예제가 없다면 구글 캘린더 관련 예제, 인증 예제를 분리하여 최대한 간단하게 구현함. 조금씩 옮기면서 되는 것을 확인하고 작업함. 이러한 과정을 _마일스톤_ 이라고 함

===== 영어 공부
* 영어를 통해 궁극적으로 하고자 하는 것이 무엇인가? 결국은 잘하고 싶은 것을 연습하는 것이 중요함
* 잘하고자 하는 것에 대해 최대한 상황을 만들어야 함

===== 프로그래밍 기초

----
* 질문

안녕하세요? 저는 이번에 컴퓨터공학과로 편입하게 되는 학생입니다.

저는 여러 이유로 컴퓨터 공학에 매력을 느끼고 소프트웨어 개발자가 되고 싶어 편입했습니다.
3학년으로 들어가는데, 프로그래밍이나 컴퓨터과학 지식이 없습니다.
그래서 가능한 한 빠르고 효율적으로 공부하고 싶어 틈틈이 알아 보던 중 애자일 이야기 블로그를 발견하고 이 강의도 알게 됬습니다.

제가 입학전 3월전까지 목표로 하는것은 두 가지 인데요.
1. 프로그래밍의 기초를 닦는 것
파이썬 -> c언어
2. 주요 전공과목을 미리 어느 정도 이해, 암기, 숙달 시켜놓는 것
자료구조, 알고리즘, 컴퓨터네트워크 등등

문제는 이 강의중 나왔던
1. 의도적 수련을 적용하고, 예시 중"파이썬 -> c언어" 순으로 프로그래밍해 좋은 결과를 얻었던 분의 방법대로 해보자 하고 접근을 하려는데 막상 시작하려니 목적에 따라 교재가 다르고, 같은 목적의 교재라도 뭐가 좋고 뭐가 나쁜지 구별이 안 되어 어떤 교재로 시작해야 할지 감도 못 잡겠습니다. 그리고 생각하다 보니 이 강의에서 소개된 방법에 적합한 기초교재도 존재할 것 같았고, 존재한다면 알고 계실 거 같아 추천을 부탁합니다.

// 첫 번째 질문 답변
안타깝게도 제가 아는 한에서 제가 소개한 방법에 적합한 기초교재가 흔하지 않습니다. 요즘 서적은 어떤지 제가 직접 확인을 해보지 않았는데, 온라인서점에서 몇 권 책을 검색해 목차를 보니 대동소이합니다.
목차로 봤을 때 그나마 좀 다르다고 느껴지는 책으로
* 헤드 퍼스트 파이썬 http://www.yes24.com/24/goods/5847218?scode=032&OzSrank=11
* Explorations in Computing http://www.amazon.com/Explorations-Computing-Introduction-Computer-Textbooks/dp/1439812624
* Introduction to Computing and Programming in Python http://www.amazon.com/Introduction-Computing-Programming-Python-4th/dp/0134025547
가 있네요. 찾아보시면 더 있을 듯싶습니다.

이렇게 말씀을 드리긴 했는데, 제가 권해 드리고 싶은 방법은 오히려 아래와 같습니다.
1) 최고의 책을 구해 그걸로 공부할 생각보다 서로 성격이 다른 여러 개를 구해 비교해 가며 공부한다는 마음을 가진다
2) 대형 서점에 가서 비슷한 주제를 다루는 서로 다른 스타일의 책들을 비교해보면서 뭔가 내 맘에 들고 끌리는 책들을 서너 권 고른다
3) 그 책들을 공부할 때 목차 순서로 간다면 한 책으로 한 챕터 읽고 다른 책으로 해당 내용이 있는 부분을 찾아서 다시 읽는다
4) 목차 순서로 가지 않는다면 목차를 훑어보고 흥미로운 부분을 골라 읽는다 (순서는 크게 신경 쓰지 않는다)
5) 책을 어떻게 읽느냐가 무척 중요하다 -- 조금 읽고 조금 시험을 쳐 보고(책 덮고 소스코드 재생해내기) 조금 응용/실험해 보고를 반복한다

2. 또 프로그래밍과 컴퓨터과학은 다르다고 들었습니다. 전공 공부에서 대학별로 커리큘럼이 겹치고 필수적인 부분을 먼저 공부하려고 하는데 위에 쓴 몇 가지 말고도 전공이 꽤 많던데 가장 필수적인 과목들과 그에 따른 가장 좋은 교재를 추천 부탁드립니다.
혹은 이 계획들 외에 더 좋은 길이 있으시면 추천해주시면 좋겠습니다.
감사합니다.

// 두 번째 질문 답변
(아래 내용은 제가 월간 마소 2001년 4월호 특집 "프로그램, 프로그래밍, 프로그래머" 기사에 썼던 내용을 기반으로 수정하고 더 추가했습니다)
어떤 주제와 과목이 소프트웨어 개발자에게 중요한지에 대하여 연구들이 있습니다. 
Lethbridge, 2000, What knowledge is important to a software professional? (Computer, May, 2000)

북미지역 및 유럽의 소프트웨어 전문가(평균 10년 정도 종사한 사람들로 프로젝트 관리자나 프로그래머들) 200여 명에게 몇 가지 질문하고 그 결과를 분석한 결과입니다. 대학에서 배운 것 중 어떤 것이 실제로 도움이 많이 되는지 등을 물었습니다. 

(http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=841783 및 http://portal.acm.org/citation.cfm?id=621473)

다음은 졸업 후 중요하게 느꼈던 주제 탑20입니다(전체 75개 주제 중 가장 중요한 것부터 내림 차순):
* 특정 프로그래밍 언어들 
* 자료 구조 
* 소프트웨어 디자인과 패턴 
* 소프트웨어 아키텍처 
* 요구사항 수집 및 분석 
* HCI(Human Computer Interaction) 및 유저 인터페이스 
* 객체 지향 기술 및 개념 
* 직업윤리와 프로페셔널리즘 
* 분석 및 디자인 방법 
* 청중에게 프레젠테이션하는 것 
* 프로젝트 관리 
* 테스팅, 검증 및 QA(Quality Assurance) 
* 알고리즘 설계 
* 기술적 글쓰기(Technical Writing) 
* 운영체제 
* 데이터베이스 
* 리더쉽 
* 형상 및 릴리즈 관리 
* 데이터 전송과 네트워크 
* 경영 

비전공자들이 일을 해오면서 ‘전문가’가 되기 위해 자신들이 가장 많이 배워야 했던 것도 물었습니다. 특정 프로그래밍 언어들, 자료 구조, 테스팅, 검증 및 QA, 운영체제, 소프트웨어 디자인 및 패턴, 객체지향 기술 및 개념, 데이터베이스, 형상관리, 직업윤리 및 프로페셔널리즘 등이었습니다.
Surakka, 2007, What subjects and skills are important for software developers? (CACM, Jan, 2007)

위 레스브릿지 연구의 업데이트판입니다. 더 최근 연구이지만 조사한 사람 숫자는 많지 않습니다. 하지만 의미있는 사람들을 조사했습니다. 핀란드의 "탁월한" 개발자 몇 명을 선정해서 델파이 방법을 통해 결과를 얻었습니다. 교수가 생각하는 중요한 주제와 대학원생이 생각하는 중요한 주제도 조사되었습니다. (http://portal.acm.org/citation.cfm?id=1188913.1188920)

두 번째 논문에 보면(75쪽 도표) 실제 뛰어난 개발자, 혹은 경력 있는 개발자(레스브릿지의 연구결과), 교수, 대학원생 등이 중요하게 여기는 소프트웨어 개발 관련 주제들과 주제별 중요도 점수가 나와 있습니다. 레스브릿지의 결과와 크게 다르지는 않습니다. 인터넷의 중요성이 높아졌다는 점 정도가 차이라고 할 수 있겠죠.
대학원 진학 예정이건, 혹은 취업이 목표이건 "프로그래밍을 잘하는 것"이 여러모로 유리하기 때문에 현직 개발자가 졸업 후 중요하게 느낀 과목들을 유심히 봐야 하겠죠.
개별 과목별 가장 좋은 책에 대해서는 앞에 썼던, 제가 권하는 방법들을 역시 여기에서도 똑같이 권합니다.
예전에 알고리즘, 자료구조, 디자인패턴 등에 관해 책 추천을 하고 공부법을 쓴 기사가 있기는 합니다. 월간 마소 2002년 6월호 기사였습니다. 제목은 "어떻게 공부할까?: 프로그래머를 위한 공부론"입니다.

위 두 기사는 pdf 파일을 공유해 드립니다.

"프로그램, 프로그래밍, 프로그래머" https://drive.google.com/file/d/0B-c4G2cSUoZvZGc1bW90ZWJtdUU/view?usp=sharing
"어떻게 공부할까: 프로그래머를 위한 공부론" https://drive.google.com/file/d/0B-c4G2cSUoZvalJWd2l1SU5UTWs/view?usp=sharing


불확실성이 높을 때에는 애자일 방법론을 쓰는 것이 좋다고 생각합니다. 학습에도 마찬가지로요. 완벽한 청사진을 구할 때까지 기다리기보다 우선 현재 자신에게 가까운 자원들(사람, 자료, 내 강점, 취미 등)을 활용해서 실험을 하고 그 피드백을 통해 계획을 조정하고 하는 것을 짧은 주기로(예컨대 한 달에 한 번씩 공부 계획을 점검한다거나) 반복해 보기를 권하고 싶네요.

특히 편입하셔서 같은 과 동기들과, 또 선배, 교수님 중에서 내가 배울 점이 있는 사람들과 친해지시는 것이 굉장히 중요할 것으로 생각합니다. 입학식 하기 전부터도 찾아보면 그 사람들과 가까워질 기회가 있으리라 생각합니다. 그들로부터 얻는 정보가 책 몇 권의 중요성을 넘어서지 않을까 합니다. ^^; 관련하여 제가 블로그에 쓴 글을 참고하세요. http://agile.egloos.com/5827377
----

===== 강연에서 효과보기 
* `컨퍼런스와 강연에서 본전 뽑기 링크 참고`
* 시연을 보기 전 연습. 시연을 보면서 따라 함. 그리고 정리함
** 강의 목차가 있다면 나라면 어떻게 할 것인가?
* 예를 들어 디자인 패턴 책 내용 중에서 Adapter 패턴을 학습한다면 책을 이해하는 것뿐만 아니라 과거 경험에도 이 패턴을 어떤 상황에서 적용했으면 좋을까? 과거, 가까운 미래에서 사례를 찾아봄

===== OOP 훈련

----
1. 일단 문제 해결에 집중
2. 해당 문제를 정확히 해결했다는 것이 확인되면
3. 다시 두어 번 작성해서(자신이 전에 짠 소스코드 보지 않고) 자신감이 생길 때까지 반복
4. 이 수준이 되면, 이제는 이미 작성한 코드를 깔끔하게 다듬는 것(리팩토링)을 시도
5. 단, 조금씩 변경시켜 가야 하고, 변경 하나 할 때마다 정상 동작하게 하여야 하며, 그 여부를 계속 확인해나가야 함
6. 그리고 다음 문제로 진행
----

=== 참고
* https://mindscale.kr/course/how-to-learn-prg/1[김창준님 - 프로그래밍, 어떻게 공부할 것인가?]
* http://agile.egloos.com/category/미분류[김창준님 - 애자일 이야기]
* http://agile.egloos.com/m/3111334[나는 왜 학습을 이야기하는가?]
* http://egloos.zum.com/agile/v/5818960[아무리 노력해도 선천적 재능을 따라잡기 힘들다?]
* http://egloos.zum.com/agile/v/2843230[자기계발이 복리로 돌아온다]
* http://agile.egloos.com/m/1762301[더 많은 일을 하면서 더 빨리 하기]
* http://agile.egloos.com/m/2035186[세계적인 수학자들은 어떻게 사고하나?]
* http://agile.egloos.com/m/4407296[꼼꼼한 번역]
* http://www.ac2.kr/reading/technical-reading[추천 도서]
* http://agile.egloos.com/m/5685603[학습 프레임과 실행 프레임]
* http://agile.egloos.com/m/5737343[불성실한 사람들을 위한 변명]
* http://agile.egloos.com/m/5774862[실수는 예방하는 것이 아니라 관리하는 것이다]
* http://agile.egloos.com/m/5829103[탐색적 논문 읽기]
* http://agile.egloos.com/m/5830026[스터디 모임 방법 몇 가지]
* http://agile.egloos.com/m/5840753[교육을 받았는데 왜 활용 못해]
* http://agile.egloos.com/m/5881049[외적 동기가 내적 동기를 갉아먹는다]
* http://agile.egloos.com/m/1686333[재미있게 공부하기]
* http://agile.egloos.com/5749946[당신이 제자리 걸음인 이유: 지루하거나 불안하거나]
* http://agile.egloos.com/5853241[컨퍼런스와 강연에서 본전 뽑기]
* https://happybono.wordpress.com/2017/10/23/cornell-식-노트-필기법과-onenote-활용법-효율적인-노트-필기-노/[Cornell Note]
* http://m.cafe.daum.net/moduenglish/1Zsh/282?q=D_sqHS-cVjpaE0&[Anki라는 소프트웨어는 SRS(Spaced Repetition System) 프로그램]