= 2018.03.05 - 2018.03.11

=== 이번 주까지 끝내야 할 일
* [ ] App Programming Guide for iOS 읽고 정리하기
* [ ] PhotoFrame 체크리스트 정리하기
* [ ] XCode 정리하기

=== 2018.03.05

===== 할 일
* [*] PhotoFrame 4 - 6단계 진행하기 
* [*] WireFrame 작성하기

===== 느낀 점
* JK가 말한 간단한 설계 규칙을 참고하여 나만의 기준 만들기

----
> 간단한 설계 규칙 (우선순위)

1. 테스트를 통과할 것(상)
- 테스트 코드는 자신의 코드가 어떤 동작을 해야 하는지 명확하도록 도와줌
- 테스트 코드를 통과하는 모듈을 작성하는 것은 TDD가 아니더라도 필요함
- 테스트가 가능하고 테스트가 쉬운 구조가 좋은 구조

2. 의도를 드러낼 것(중)
- 변수이름, 함수이름, 클래스이름에서도 의도를 표현해야 함
- private 인지 public 인지 선언한 속성에 대해서도 명확한 의도가 있어야 함

3. 중복을 제거할 것(중)
- 중복된 코드가 보이면 메소드를 분리하거나 타입을 분리하거나 객체를 분리해서 중복을 제거해야 함
- 메소드 인터페이스가 동일하면 프로토콜을 활용하고, 구현 내용은 같고 타입만 다르면 제네릭을 활용함

4. 구성 요소를 최소화할 것(하)
- 함수의 매개변수, 객체의 속성이나 메소드도 꼭 필요한 경우에 추가함
- 명확한 역할이 없는 구성요소는 존재 의미도 없는 경우가 많음. 자신의 의도를 다시 한 번 고민해보기
----

* 처음이니깐 잘하려는 생각을 버리고 WireFrame 완성해보자:)

=== 2018.03.06

===== 할 일 
* [*] PhotoFrame 6-7단계 진행하고 정리한 내용 다시보기
* [*] Wireframe - 책 보여주는 상세화면 만들기
* [*] Android, iOS, UX/UI 관련 1일 1포스트 읽고 핵심키워드 정리하기
* [*] 스케치, UX/UI 스터디 참가하기

====== 느낀 점
* 스케치, UX/UI 스터디 참가하면서 내가 얻고자 하는 것은 앱 개발에 필요한 기획, 디자인 결과물, 스케치 앱 다루기라는 것을 잊지 말자!

=== 2018.03.07

===== 할 일
* [*] 앱 기획 내용, Wireframe, 화면별 핵심 기능을 키노트로 정리하기
* [*] SLIPP 발표 준비하기
* [*] Android, iOS, UX/UI 관련 1일 1포스트 읽고 핵심키워드 정리하기

===== 느낀 점
* 앱 기획에 대한 JK's feedbacks

----
* 사용성
    * 동등한 수준의 화면이면 탭바로, 앞뒤로 더 세부적인 화면이면 내비게이션으로
    * 메인 화면이 그 앱의 핵심 기능이어야 함
    * 3화면 이상 들어가면 사용자들은 어려워 함
    * 버튼 위치도 애플 앱이나 유명한 앱들처럼 익숙한 위치에 하는게 좋음

* 기술
    * 아이클라우드 백업은 앱내 Document 디렉토리는 백업 대상임. 거기에 파일을 만들면 자동 백업
    * iCloud KeyValue 혹은 iCloud Document 기술도 사용함
    * 백엔드가 필요한 경우는 내정보/혹은 다른사람 데이터를 서로 봐야하는가? 
    * 서버가 없어도 iCloudKit 이나 firebase 같은 BaaS도 고려해볼 것
    * 오픈 API 한계는 무엇인가? 얼마나 자주 보낼수 있나. 뭐가 되고 뭐가 안되는가..

* 기타 
    * 산책: 쳬계적 도서 관리 (제작사 별책) 
    * 밀리의 서재 
    * 교보문고 - 인식기가 가장 좋은 평가를 받음


* 참고 예제
제주도감 앱스토어 https://itunes.apple.com/kr/app/%EC%A0%9C%EC%A3%BC%EB%8F%84%EA%B0%90/id1199806926?l=en&mt=8

기획서 https://www.dropbox.com/s/auqmaiddy4l91kn/%EC%A0%9C%EC%A3%BC%EB%8F%84%EA%B0%90_%EA%B8%B0%ED%9A%8D%EC%84%9C.pdf?dl=0

스토리보드 https://www.dropbox.com/s/uum0wi62007nl0g/%EC%A0%9C%EC%A3%BC%EB%8F%84%EA%B0%90-%EC%8A%A4%ED%86%A0%EB%A6%AC%EB%B3%B4%EB%93%9C%201.0.pdf?dl=0

개발일정표 https://docs.google.com/spreadsheets/d/14sjp4gbyI7StNEYx4_8aYS-rWtv1YdOdw21loMVg_x0/edit#gid=0
----

=== 2018.03.08

===== 할 일
* [*] VendingMachine 1-2단계 과제 진행하기
* [*] App Programming Guide for iOS 
** [*] Introduction
** [*] Expected App Behaviors 
** [*] The App Life Cycle - The Main Function 읽고 정리하기

===== 느낀 점
* 내가 사용하는 XCode에 대해 많이 알게 되었는데 정리가 필요함

=== 2018.03.09

===== 할 일
* [ ] VendingMachine 3단계 과제 진행하기
* [ ] App Programming Guide for iOS 
** [ ] The App Life Cycle 
** [ ] Background Execution 읽고 정리하기